// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQeZjbiuHwMSNXWxH0uJ9UPXHZRh36b1w',
    appId: '1:631334287049:web:9473e469fba9513a6bbf18',
    messagingSenderId: '631334287049',
    projectId: 'megamart-final-37680',
    authDomain: 'megamart-final-37680.firebaseapp.com',
    storageBucket: 'megamart-final-37680.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-xu2cade8wZ-xRVU5uQOuYc1rsLmGVJ8',
    appId: '1:631334287049:android:fbb9612bf9650c3e6bbf18',
    messagingSenderId: '631334287049',
    projectId: 'megamart-final-37680',
    storageBucket: 'megamart-final-37680.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNP8jzmLjyVe1wY--Z8PlpD6XV4-lBOLk',
    appId: '1:631334287049:ios:a4e54227fe1ff2846bbf18',
    messagingSenderId: '631334287049',
    projectId: 'megamart-final-37680',
    storageBucket: 'megamart-final-37680.appspot.com',
    iosBundleId: 'com.example.megamart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNP8jzmLjyVe1wY--Z8PlpD6XV4-lBOLk',
    appId: '1:631334287049:ios:a4e54227fe1ff2846bbf18',
    messagingSenderId: '631334287049',
    projectId: 'megamart-final-37680',
    storageBucket: 'megamart-final-37680.appspot.com',
    iosBundleId: 'com.example.megamart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQeZjbiuHwMSNXWxH0uJ9UPXHZRh36b1w',
    appId: '1:631334287049:web:14c1c7cfd6f6d1296bbf18',
    messagingSenderId: '631334287049',
    projectId: 'megamart-final-37680',
    authDomain: 'megamart-final-37680.firebaseapp.com',
    storageBucket: 'megamart-final-37680.appspot.com',
  );
}
